name: Auto Assign

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto-assign-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
